name: optionxi
description: Stock Research App
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.3+4

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter

   # FG
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.0
  otp_text_field: ^1.0.0
  lottie: ^2.3.2
  flutter_animate: ^4.5.2
  provider: ^6.1.2
  # flutter_search_bar: ^2.0.7
  readmore: ^2.1.0
  badges: ^3.1.1
  transparent_image: ^2.0.0
  # carousel_slider: ^3.0.0 
  flutter_staggered_grid_view: ^0.4.1
  flutter_switch: ^0.3.2
  # video_player: ^2.2.2
  # carousel_pro: ^1.0.0
  intl_phone_field: ^3.1.0
  screen_protector: ^1.4.2

  intl: ^0.19.0
  get: ^4.5.1
  get_storage: ^2.0.3
  timeago: ^3.7.0
  full_screen_image: ^2.0.0
  font_awesome_flutter: ^10.1.0

  

  path_provider: ^2.0.4
  animations: ^2.0.2
  

  shared_preferences: ^2.2.3
  # open_file_plus: ^3.4.1
  open_file_plus:
    git:
      url: https://github.com/postflow/open_file_plus
  url_launcher: ^6.3.1

  flutter_html: ^3.0.0-beta.2
  in_app_purchase: ^3.1.5
  in_app_purchase_storekit: 0.3.8  # Use older stable version

  # sign_in_with_apple: ^5.0.0
  sign_in_with_apple: ^7.0.1

  dio: ^5.8.0+1

  firebase_auth: ^5.5.2
  firebase_database: ^11.3.5
  firebase_remote_config: ^5.4.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.1+3
  firebase_analytics: ^11.4.5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0

  supabase_flutter: ^2.8.4

  google_sign_in: ^6.1.0
  # google_mobile_ads: ^4.0.0
  google_fonts: ^4.0.4
  # permission_handler: ^10.2.0
  permission_handler: ^12.0.0+1
  # photo_view: ^0.14.0
  photo_view: ^0.12.0
  flutter_slidable: ^3.1.0
  syncfusion_flutter_charts: ^29.1.39
  webview_flutter: ^4.4.2

  # algolia: ^1.1.2
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  sqflite: ^2.3.2
  # chatwoot_client_sdk: ^0.0.8
  # chatwoot_sdk: ^0.0.9
  # chatwoot_sdk:
  #   git:
  #     url: https://github.com/katmakhan/chatwoot-flutter-sdk.git
  #     ref: 188444d90dd89062ef8eb587be224a75f5c88cb5

  
  flutter_document_picker:
    git:
      url: https://github.com/katmakhan/flutter_document_picker.git
      ref: master
      
  flutter_datetime_picker:
    git:
      url: https://github.com/katmakhan/flutter_datetime_picker.git
      ref: master


  smooth_page_indicator: ^1.0.0+2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  package_info_plus: ^4.0.0
  # appinio_video_player: ^1.3.0
  flutter_markdown: ^0.6.19
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2 



# flutter_icons:
#   android: true
#   ios: true
#   remove_alpha_ios: true
#   # image_path: "assets/images/applogo.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   adaptive_icon_background: "#ffffff"
#   adaptive_icon_foreground: "assets/images/logo_foreground.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 200
        - asset: fonts/Inter-Medium.ttf
          weight: 300  
        - asset: fonts/Inter-SemiBold.ttf
          weight: 400  
        - asset: fonts/Inter-Bold.ttf
          weight: 500  
        - asset: fonts/Inter-Black.ttf
          weight: 600
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 700 
    - family: Montserrat
      fonts:     
        - asset: fonts/Montserrat-Regular.ttf
          weight: 300  
        - asset: fonts/Montserrat-Medium.ttf
          weight: 400  
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: fonts/Montserrat-Bold.ttf
          weight: 600  
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 700
        - asset: fonts/Montserrat-Black.ttf
          weight: 800    
        
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages