name: Gitleaks Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 👈 Important: Fetch full history for Gitleaks

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --config-path=.gitleaks.toml --redact
