name: TruffleHog Secret Scan

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run TruffleHog Scan
        uses: trufflesecurity/trufflehog@main
        with:
          scanArguments: --source .
